"use strict";

const ephLogo = new URL('../assets/eph-logo.png', import.meta.url).href;

class UiFooter extends HTMLElement {
  connectedCallback() {
    if (this.firstElementChild) return;

    this.innerHTML = `
      <footer class="footer">
        <div class="footer-brand">
          <img src="${ephLogo}" onerror="this.onerror=null; this.src='https://ebookweb.ephhk.com/assets/images/ephhk-logo.png';" alt="Educational Publishing House" class="footer-logo">
        </div>
        <div class="footer-disclaimer">
          <span data-lang-content="zh">本內容由教育出版社 e-Smart.AI 所生成，其準確性未必能達到百分之百。教師在採用任何 AI 生成之內容前，請務必以專業判斷進行審核與驗證；學生如對內容有任何疑問，請尋求老師或家長的協助。</span>
          <span data-lang-content="en" hidden>This content is generated by Educational Publishing House e-Smart.AI. Its accuracy may not be 100%. Teachers must exercise their professional judgement to review and verify before using any AI-generated content. If students have any questions regarding the content, please seek assistance from teachers or parents.</span>
        </div>
      </footer>
    `;
  }
}

if (!customElements.get("ui-footer")) {
  customElements.define("ui-footer", UiFooter);
}
