"use strict";

class UiFooter extends HTMLElement {
  connectedCallback() {
    if (this.firstElementChild) return;

    this.innerHTML = `
      <footer class="footer">
        <div class="footer-brand">
          <img src="assets/eph-logo.png" onerror="this.onerror=null; this.src='https://ebookweb.ephhk.com/assets/images/ephhk-logo.png';" alt="Educational Publishing House" class="footer-logo">
        </div>
        <div class="footer-disclaimer">
          <span data-lang-content="zh">本內容由教育出版社 e-Smart.AI 所生成，其準確性未必能達到百分之百。教師在採用任何 AI 生成之內容前，請務必以專業判斷進行審核與驗證；學生如對內容有任何疑問，請尋求老師或家長的協助。</span>
          <span data-lang-content="en" hidden>This content was generated by e-Smart.AI of Educational Publishing House Limited and may not be entirely accurate. Teachers should carefully review and verify it using their professional judgment before adopting it. Students with questions about the content are encouraged to consult their teachers or parents.</span>
        </div>
      </footer>
    `;
  }
}

if (!customElements.get("ui-footer")) {
  customElements.define("ui-footer", UiFooter);
}
